apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configmap-app-shivambindal
  namespace: kubernetes-cluster-shivambindal
  labels:
    app: node-shivambindal-master
data:
  API_URL: "http://google.com"
  ENVIRONMENT: "Master"

---
apiVersion: v1
kind: Secret
metadata:
  name: node-secret-app-shivambindal
  namespace: kubernetes-cluster-shivambindal
  labels:
    app: node-shivambindal-master
data:
  DB_PASSWORD: "YWRtaW4="
  DB_USERNAME: "YWRtaW4="
type: Opaque

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-shivambindal-master-deployment
  namespace: kubernetes-cluster-shivambindal
  labels:
    app: node-shivambindal-master
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-shivambindal-master
  template:
    metadata:
      labels:
        app: node-shivambindal-master
    spec:
      containers:
        - name: node-shivambindal-master
          image: nagpshivam/i-shivambindal-master:latest
          ports:
            - name: http
              containerPort: 7100
              protocol: TCP
          envFrom:
          - configMapRef:
              name: node-configmap-app-shivambindal
          - secretRef:
              name: node-secret-app-shivambindal

---

apiVersion: v1
kind: Service
metadata:
  name: node-shivambindal-master
  namespace: kubernetes-cluster-shivambindal
spec:
  type: LoadBalancer
  selector:
    app: node-shivambindal-master
  ports:
  - targetPort: 7100
    port: 81
    protocol: TCP
    nodePort: 30081
