apiVersion: v1
kind: Secret
metadata:
  name: node-secret-app-shivambindal
  namespace: kubernetes-cluster-shivambindal
  labels:
    app: node-app-shivambindal
data:
  DB_PASSWORD: "YWRtaW4="
  DB_USERNAME: "YWRtaW4="