apiVersion: v1
kind: Secret
metadata:
  name: node-secret-app-shivambindal
  namespace: kubernetes-cluster-shivambindal
  labels:
    app: node-shivambindal-develop
data:
  DB_PASSWORD: "YWRtaW4="
  DB_USERNAME: "YWRtaW4="
type: Opaque